[package]
name = "hj-config"
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
quick-xml = { workspace = true, features = ["serialize"] }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
