[package]
name = "hj-extension"
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
hj-core = { workspace = true }
async-trait = { workspace = true }
http = { workspace = true }
thiserror = { workspace = true }
