name: Actions policy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  policy:
    uses: faratech/ci-standards/.github/workflows/actions-policy.yml@main
    with:
      policy_strict: false
